name: "Open Github Issue"
description: "Open Github Issue"
author: "David Koch"

# Define your inputs here.
inputs:
  token:
    description: "Github Token"
    required: true
  title:
    description: "Issue Title"
    required: true
  body:
    description: "Issue Body"
  assignees:
    description: "Issue Assignees"
    
# Define your outputs here.
outputs:
  issue:
    description: "The issue object as a json string"

runs:
  using: node20
  main: dist/index.js
